### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by pattyland** [k0rventen/avea#6]
Got this strange errors a few times lately, not sure wether this avea or bluepy:

```
2019-11-08 00:30:34 ERROR (MainThread) [homeassistant.components.light] Error while setting up platform avea
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/avea/light.py", line 24, in setup_platform
    nearby_bulbs = avea.discover_avea_bulbs()
  File "/usr/local/lib/python3.7/site-packages/avea/avea.py", line 237, in discover_avea_bulbs
    devices = scanner.scan(4.0)
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 852, in scan
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 790, in start
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 309, in _mgmtCmd
    DBG("Select timeout")
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 352, in _waitResp
    elif deviceAddr is not None:
  File "/usr/local/lib/python3.7/site-packages/bluepy/btle.py", line 318, in parseResp
    if 'rsp' not in resp:
ValueError: too many values to unpack (expected 2)
```

**Comment by pattyland** [comment]
As this seems to more problem of bluepy I opened an issue there: https://github.com/IanHarvey/bluepy/issues/387
